-- Generated by ERDone (SQL Server)
-- 2026-07-18T01:34:04.108Z

CREATE TABLE [Assembly] (
  [Assembly_ID] INT NOT NULL,
  [Part_Number] VARCHAR(50) NOT NULL,
  [Drawing_Number] VARCHAR(50) NOT NULL,
  [Revision] VARCHAR(10) NOT NULL,
  [Quote_Number] INT NOT NULL,
  [Description] VARCHAR(100) NOT NULL,
  CONSTRAINT [PK_Assembly] PRIMARY KEY ([Assembly_ID])
);
GO

CREATE TABLE [Assembly_service] (
  [AS_ID] INT NOT NULL,
  [Service_ID] INT NOT NULL,
  [Notes] VARCHAR(500) NOT NULL,
  [AssemblyID] INT NOT NULL,
  CONSTRAINT [PK_Assembly_service] PRIMARY KEY ([AS_ID])
);
GO

CREATE TABLE [] (
  [Quote_Number] NVARCHAR(MAX) NOT NULL,
  [Customer] NVARCHAR(MAX) NOT NULL,
  CONSTRAINT [PK_] PRIMARY KEY ([Quote_Number])
);
GO

CREATE TABLE [Assembly_Purchased_Components] (
  [PC_ID] NVARCHAR(MAX) NOT NULL,
  [Assembly_ID] NVARCHAR(MAX) NOT NULL,
  [Component_ID] NVARCHAR(MAX) NOT NULL
);
GO

CREATE TABLE [Assembly_Stock_Material] (
  [ASM_ID] INT NOT NULL,
  [Material_ID] INT NOT NULL,
  [Assembly_ID] INT NOT NULL,
  CONSTRAINT [PK_Assembly_Stock_Material] PRIMARY KEY ([ASM_ID])
);
GO

CREATE TABLE [component] (
  [component_ID] INT NOT NULL,
  [Description] VARCHAR(100) NOT NULL,
  [Price] DECIMAL(18, 2) NOT NULL,
  [Vendor] VARCHAR(100) NOT NULL,
  [Notes] VARCHAR(500) NOT NULL
);
GO

-- Foreign key constraints
ALTER TABLE [Assembly_service] ADD CONSTRAINT [FK_Assembly_service_AssemblyID] FOREIGN KEY ([AssemblyID]) REFERENCES [Assembly] ([Assembly_ID]);
GO
ALTER TABLE [Assembly_Purchased_Components] ADD CONSTRAINT [FK_Assembly_Purchased_Components_Assembly_ID] FOREIGN KEY ([Assembly_ID]) REFERENCES [Assembly] ([Assembly_ID]);
GO
ALTER TABLE [component] ADD CONSTRAINT [FK_component_component_ID] FOREIGN KEY ([component_ID]) REFERENCES [Assembly_Purchased_Components] ([Component_ID]);
GO

-- Indexes
CREATE INDEX [IX_Assembly_service_AssemblyID] ON [Assembly_service] ([AssemblyID]);
GO
CREATE INDEX [IX_Assembly_Purchased_Components_Assembly_ID] ON [Assembly_Purchased_Components] ([Assembly_ID]);
GO
CREATE INDEX [IX_component_component_ID] ON [component] ([component_ID]);
GO
