-- Generated by ERDone (SQL Server)
-- 2026-07-18T01:16:00.160Z

CREATE TABLE [Assembly] (
  [Assembly_ID] NVARCHAR(MAX) NOT NULL,
  [Part_Number] NVARCHAR(MAX) NOT NULL,
  [Drawing_Number] NVARCHAR(MAX) NOT NULL,
  [Revision] NVARCHAR(MAX) NOT NULL,
  [Quote_ID] NVARCHAR(MAX) NOT NULL,
  CONSTRAINT [PK_Assembly] PRIMARY KEY ([Assembly_ID])
);
GO

CREATE TABLE [Assembly_service] (
  [Assembly_ID] NVARCHAR(MAX) NOT NULL
);
GO

CREATE TABLE [] (
  [Quote_Number] NVARCHAR(MAX) NOT NULL,
  [Customer] NVARCHAR(MAX) NOT NULL,
  CONSTRAINT [PK_] PRIMARY KEY ([Quote_Number])
);
GO

CREATE TABLE [Assembly_Purchased_Components] (
  [PC_ID] NVARCHAR(MAX) NOT NULL
);
GO
