-- Generated by ERDone (SQL Server)
-- 2026-07-17T03:12:40.071Z

CREATE TABLE [Customer] (
  [CustomerId] INT NOT NULL IDENTITY(1, 1),
  [name] VARCHAR(50) NOT NULL,
  [Created_ON] DATETIME2 DEFAULT now() NOT NULL,
  [Last_Updated] DATETIME2 NOT NULL,
  CONSTRAINT [PK_Customer] PRIMARY KEY ([CustomerId])
);
GO
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'Application end users with shipping and billing addresses.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'Customer';
GO

CREATE TABLE [Customer Addresses] (
  [AddressId] INT NOT NULL IDENTITY(1, 1),
  [CustomerId] INT NOT NULL,
  [Line1] VARCHAR(120) NOT NULL,
  [Line2] VARCHAR(120) NULL,
  [City] VARCHAR(60) NOT NULL,
  [State] VARCHAR(30) NOT NULL,
  [PostalCode] VARCHAR(20) NOT NULL,
  [IsBilling] BIT DEFAULT false NOT NULL,
  [IsShipping] BIT NOT NULL,
  [Address_Id] VARCHAR(MAX) NOT NULL,
  CONSTRAINT [PK_Customer Addresses] PRIMARY KEY ([AddressId])
);
GO
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'Shipping and billing addresses belonging to a customer.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'Customer Addresses';
GO

CREATE TABLE [SalesOrder] (
  [Order_ID] INT NOT NULL IDENTITY(1, 1),
  [CustomerId] INT NOT NULL,
  [Order_Date] DATETIME2 DEFAULT now() NOT NULL,
  [StatusCode] VARCHAR(20) DEFAULT 'pending' NOT NULL,
  [Address_Id] VARCHAR(MAX) NOT NULL,
  [terms] VARCHAR(MAX) NOT NULL,
  [Customer_Contact_ID] NVARCHAR(MAX) NOT NULL,
  [Created_On] DATETIME2 NOT NULL,
  [Last_Updated] DATETIME2 NOT NULL,
  CONSTRAINT [PK_SalesOrder] PRIMARY KEY ([Order_ID])
);
GO
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'Customer purchases. Total is denormalized from OrderItems for fast list views.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'SalesOrder';
GO

CREATE TABLE [Sales_Order_Item] (
  [SO_Item_ID] INT NOT NULL,
  [OrderId] INT NOT NULL,
  [LineNum] INT NOT NULL,
  [Part_Number] INT NOT NULL,
  [Quantity] INT DEFAULT 1 NULL,
  [UnitPrice] DECIMAL(10, 2) NULL,
  [Description] VARCHAR(120) NULL,
  [Rev] VARCHAR(12) NOT NULL,
  [Created_On] DATETIME2 NOT NULL,
  [Last_updated] DATETIME2 NOT NULL,
  CONSTRAINT [PK_Sales_Order_Item] PRIMARY KEY ([SO_Item_ID])
);
GO
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'Line items on an order; a weak entity identified by its order plus a line sequence number.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'Sales_Order_Item';
GO

CREATE TABLE [customer_contact] (
  [Customer_Contact_Id] INT NOT NULL,
  [CustomerId] INT NOT NULL,
  [Contact_Name] VARCHAR(MAX) NOT NULL,
  [Email_Address] VARCHAR(MAX) NOT NULL,
  [Phone_Number] NVARCHAR(MAX) NOT NULL,
  CONSTRAINT [PK_customer_contact] PRIMARY KEY ([Customer_Contact_Id])
);
GO
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'table of customer contacts', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'customer_contact';
GO

CREATE TABLE [Job] (
  [Job_ID] VARCHAR(20) NOT NULL,
  [Created_ON] DATE NOT NULL,
  [Last_Updated] DATE NOT NULL,
  [OrderID] INT NOT NULL,
  [LineNum] INT NOT NULL,
  [Parent_Job] VARCHAR(20) NULL,
  [Top_Level_Job] VARCHAR(20) NOT NULL,
  CONSTRAINT [PK_Job] PRIMARY KEY ([Job_ID])
);
GO

CREATE TABLE [Job_Saw_Cut] (
  [ID] INT NOT NULL,
  [Job_ID] VARCHAR(20) NOT NULL,
  [Part_Number] VARCHAR(40) NOT NULL,
  [Qty] INT NOT NULL,
  [length] DECIMAL(18, 2) NOT NULL,
  [Material] VARCHAR(MAX) NOT NULL,
  CONSTRAINT [PK_Job_Saw_Cut] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [Job_Plasma_Cut] (
  [ID] INT NOT NULL,
  [Job_ID] VARCHAR(20) NOT NULL,
  [Part_Number] VARCHAR(40) NULL,
  [Item_Number] VARCHAR(20) NULL,
  [Material] VARCHAR(20) NOT NULL,
  [Total_Qty] INT NOT NULL,
  [Length] DECIMAL(18, 2) NOT NULL,
  [Width] DECIMAL(18, 2) NOT NULL,
  [Still_Need_To_Cut] INT NOT NULL,
  [sq_In] DECIMAL(18, 2) NOT NULL,
  [Heat_Number] VARCHAR(40) NOT NULL,
  CONSTRAINT [PK_Job_Plasma_Cut] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [Job_Component] (
  [ID] INT NOT NULL,
  [Job_ID] VARCHAR(20) NOT NULL,
  [Description] VARCHAR(40) NOT NULL,
  [Vendor] VARCHAR(20) NOT NULL,
  [qty] INT NOT NULL,
  [Unit_Price] DECIMAL(18, 2) NOT NULL,
  [extended price] DECIMAL(18, 2) NOT NULL,
  [status] VARCHAR(12) NOT NULL,
  CONSTRAINT [PK_Job_Component] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [vendor] (
  [ID] NVARCHAR(MAX) NOT NULL,
  CONSTRAINT [PK_vendor] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [Job_linstock_Nesting] (
  [ID] NVARCHAR(MAX) NOT NULL,
  [Job_ID] NVARCHAR(MAX) NOT NULL,
  [Material] NVARCHAR(MAX) NOT NULL,
  [Saw] NVARCHAR(MAX) NOT NULL,
  [Plasma] NVARCHAR(MAX) NOT NULL,
  [Stock_Length] NVARCHAR(MAX) NOT NULL,
  [Qty] NVARCHAR(MAX) NOT NULL,
  CONSTRAINT [PK_Job_linstock_Nesting] PRIMARY KEY ([ID])
);
GO

CREATE TABLE [Job_Operation] (
  [Id] INT NOT NULL,
  [Operation_Id] VARCHAR(20) NOT NULL,
  [Job_ID] VARCHAR(20) NOT NULL,
  [Est_Hours] DECIMAL(18, 2) NULL,
  [Act_Hours] DECIMAL(18, 2) NULL,
  [Proj_Hours] DECIMAL(18, 2) NULL,
  [Created_On] DATETIME2 NOT NULL,
  [Last_Updated] DATETIME2 NOT NULL,
  CONSTRAINT [PK_Job_Operation] PRIMARY KEY ([Id])
);
GO

CREATE TABLE [Job_Operation_Time] (
  [ID] NVARCHAR(MAX) NOT NULL,
  [Operation_ID] NVARCHAR(MAX) NOT NULL,
  [Employee] NVARCHAR(MAX) NOT NULL,
  [Duration] DECIMAL(18, 2) NOT NULL,
  [Created_On] DATETIME2 NOT NULL,
  [Last_Updated] DATETIME2 NOT NULL,
  CONSTRAINT [PK_Job_Operation_Time] PRIMARY KEY ([ID])
);
GO

-- Foreign key constraints
ALTER TABLE [Customer Addresses] ADD CONSTRAINT [FK_Customer Addresses_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customer] ([CustomerId]) ON DELETE CASCADE;
GO
ALTER TABLE [Customer Addresses] ADD CONSTRAINT [FK_Customer Addresses_Address_Id] FOREIGN KEY ([Address_Id]) REFERENCES [SalesOrder] ([Address_Id]);
GO
ALTER TABLE [SalesOrder] ADD CONSTRAINT [FK_SalesOrder_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customer] ([CustomerId]);
GO
ALTER TABLE [SalesOrder] ADD CONSTRAINT [FK_SalesOrder_Customer_Contact_ID] FOREIGN KEY ([Customer_Contact_ID]) REFERENCES [customer_contact] ([Customer_Contact_Id]);
GO
ALTER TABLE [Sales_Order_Item] ADD CONSTRAINT [FK_Sales_Order_Item_OrderId] FOREIGN KEY ([OrderId]) REFERENCES [SalesOrder] ([Order_ID]) ON DELETE CASCADE;
GO
ALTER TABLE [Sales_Order_Item] ADD CONSTRAINT [FK_Sales_Order_Item_LineNum] FOREIGN KEY ([LineNum]) REFERENCES [Job] ([LineNum]);
GO
ALTER TABLE [customer_contact] ADD CONSTRAINT [FK_customer_contact_CustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [Customer] ([CustomerId]);
GO
ALTER TABLE [Job] ADD CONSTRAINT [FK_Job_OrderID] FOREIGN KEY ([OrderID]) REFERENCES [SalesOrder] ([Order_ID]);
GO
ALTER TABLE [Job] ADD CONSTRAINT [FK_Job_Job_ID] FOREIGN KEY ([Job_ID]) REFERENCES [Job_Saw_Cut] ([Job_ID]);
GO
ALTER TABLE [Job] ADD CONSTRAINT [FK_Job_Job_ID] FOREIGN KEY ([Job_ID]) REFERENCES [Job_Plasma_Cut] ([Job_ID]);
GO
ALTER TABLE [Job] ADD CONSTRAINT [FK_Job_Job_ID] FOREIGN KEY ([Job_ID]) REFERENCES [Job_Component] ([Job_ID]);
GO
ALTER TABLE [Job] ADD CONSTRAINT [FK_Job_Job_ID] FOREIGN KEY ([Job_ID]) REFERENCES [Job_linstock_Nesting] ([Job_ID]);
GO
ALTER TABLE [Job] ADD CONSTRAINT [FK_Job_Job_ID] FOREIGN KEY ([Job_ID]) REFERENCES [Job_Operation] ([Job_ID]);
GO
ALTER TABLE [Job_Operation] ADD CONSTRAINT [FK_Job_Operation_Operation_Id] FOREIGN KEY ([Operation_Id]) REFERENCES [Job_Operation_Time] ([Operation_ID]);
GO

-- Indexes
CREATE INDEX [IX_Address_CustomerId] ON [Customer Addresses] ([CustomerId]);
GO
CREATE INDEX [IX_Customer Addresses_Address_Id] ON [Customer Addresses] ([Address_Id]);
GO
CREATE INDEX [IX_SalesOrder_CustomerId] ON [SalesOrder] ([CustomerId]);
GO
CREATE INDEX [IX_SalesOrder_Customer_Contact_ID] ON [SalesOrder] ([Customer_Contact_ID]);
GO
CREATE INDEX [IX_OrderItem_ProductId] ON [Sales_Order_Item] ([Part_Number]);
GO
CREATE INDEX [IX_Sales_Order_Item_LineNum] ON [Sales_Order_Item] ([LineNum]);
GO
CREATE INDEX [IX_customer_contact_CustomerId] ON [customer_contact] ([CustomerId]);
GO
CREATE INDEX [IX_Job_OrderID] ON [Job] ([OrderID]);
GO
CREATE INDEX [IX_Job_Operation_Job_ID] ON [Job_Operation] ([Job_ID]);
GO
CREATE INDEX [IX_Job_Operation_Operation_Id] ON [Job_Operation] ([Operation_Id]);
GO
