-- Generated by ERDone (PostgreSQL)
-- 2026-07-17T01:35:21.613Z

CREATE TABLE "Customer" (
  "CustomerId" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  "FirstName" VARCHAR(50) NOT NULL,
  "LastName" VARCHAR(50) NOT NULL,
  "Email" VARCHAR(120) NOT NULL UNIQUE,
  "CreatedAt" TIMESTAMP DEFAULT now() NOT NULL,
  CONSTRAINT "PK_Customer" PRIMARY KEY ("CustomerId")
);
COMMENT ON TABLE "Customer" IS 'Application end users with shipping and billing addresses.';

CREATE TABLE "Customer Addresses" (
  "AddressId" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  "CustomerId" INTEGER NOT NULL,
  "Line1" VARCHAR(120) NOT NULL,
  "Line2" VARCHAR(120) NULL,
  "City" VARCHAR(60) NOT NULL,
  "State" VARCHAR(30) NOT NULL,
  "PostalCode" VARCHAR(20) NOT NULL,
  "IsBilling" BOOLEAN DEFAULT false NOT NULL,
  "IsShipping" BOOLEAN NOT NULL,
  CONSTRAINT "PK_Customer Addresses" PRIMARY KEY ("AddressId")
);
COMMENT ON TABLE "Customer Addresses" IS 'Shipping and billing addresses belonging to a customer.';

CREATE TABLE "SalesOrder" (
  "OrderId" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  "CustomerId" INTEGER NOT NULL,
  "Order_Date" TIMESTAMP DEFAULT now() NOT NULL,
  "StatusCode" VARCHAR(20) DEFAULT 'pending' NOT NULL,
  "Address_Id" TEXT NOT NULL,
  "terms" TEXT NOT NULL,
  "Customer_Contact_ID" TEXT NOT NULL,
  CONSTRAINT "PK_SalesOrder" PRIMARY KEY ("OrderId")
);
COMMENT ON TABLE "SalesOrder" IS 'Customer purchases. Total is denormalized from OrderItems for fast list views.';

CREATE TABLE "Sales_Order_Item" (
  "SO_Item_ID" INTEGER NOT NULL,
  "OrderId" INTEGER NOT NULL,
  "LineNum" INTEGER NOT NULL,
  "Part_Number" INTEGER NOT NULL,
  "Quantity" INTEGER DEFAULT 1 NULL,
  "UnitPrice" NUMERIC(10, 2) NULL,
  "Description" TEXT NULL,
  CONSTRAINT "PK_Sales_Order_Item" PRIMARY KEY ("SO_Item_ID")
);
COMMENT ON TABLE "Sales_Order_Item" IS 'Line items on an order; a weak entity identified by its order plus a line sequence number.';

CREATE TABLE "customer_contact" (
  "Customer_Contact_Id" INTEGER NOT NULL,
  "CustomerId" INTEGER NOT NULL,
  "Contact_Name" TEXT NOT NULL,
  "Email_Address" TEXT NOT NULL,
  "Phone_Number" TEXT NOT NULL,
  CONSTRAINT "PK_customer_contact" PRIMARY KEY ("Customer_Contact_Id")
);
COMMENT ON TABLE "customer_contact" IS 'table of customer contacts';

CREATE TABLE "Job" (
  "Job_ID" VARCHAR(20) NOT NULL,
  "Created_ON" DATE NOT NULL,
  "Last_Updated" DATE NOT NULL,
  "OrderID" INTEGER NOT NULL,
  "LineNum" INTEGER NOT NULL,
  "Parent_Job" VARCHAR(20) NULL,
  CONSTRAINT "PK_Job" PRIMARY KEY ("Job_ID")
);

CREATE TABLE "Job_Saw_Cut" (
  "ID" INTEGER NOT NULL,
  "Job_ID" INTEGER NOT NULL,
  "Part_Number" TEXT NOT NULL,
  "Qty" INTEGER NOT NULL,
  "length" NUMERIC NOT NULL,
  "Material" TEXT NOT NULL
);

-- Foreign key constraints
ALTER TABLE "Customer Addresses" ADD CONSTRAINT "FK_Customer Addresses_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customer" ("CustomerId") ON DELETE CASCADE;
ALTER TABLE "SalesOrder" ADD CONSTRAINT "FK_SalesOrder_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customer" ("CustomerId");
ALTER TABLE "Sales_Order_Item" ADD CONSTRAINT "FK_Sales_Order_Item_OrderId" FOREIGN KEY ("OrderId") REFERENCES "SalesOrder" ("OrderId") ON DELETE CASCADE;
ALTER TABLE "Sales_Order_Item" ADD CONSTRAINT "FK_Sales_Order_Item_LineNum" FOREIGN KEY ("LineNum") REFERENCES "Job" ("LineNum");
ALTER TABLE "customer_contact" ADD CONSTRAINT "FK_customer_contact_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customer" ("CustomerId");
ALTER TABLE "Job" ADD CONSTRAINT "FK_Job_OrderID" FOREIGN KEY ("OrderID") REFERENCES "SalesOrder" ("OrderId");
ALTER TABLE "Job" ADD CONSTRAINT "FK_Job_Job_ID" FOREIGN KEY ("Job_ID") REFERENCES "Job_Saw_Cut" ("Job_ID");

-- Indexes
CREATE INDEX "IX_Address_CustomerId" ON "Customer Addresses" ("CustomerId");
CREATE INDEX "IX_SalesOrder_CustomerId" ON "SalesOrder" ("CustomerId");
CREATE INDEX "IX_OrderItem_ProductId" ON "Sales_Order_Item" ("Part_Number");
CREATE INDEX "IX_Sales_Order_Item_LineNum" ON "Sales_Order_Item" ("LineNum");
CREATE INDEX "IX_customer_contact_CustomerId" ON "customer_contact" ("CustomerId");
CREATE INDEX "IX_Job_OrderID" ON "Job" ("OrderID");
